//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public interface ISquareDiv
	{
		Sprite Base { get; }
		Sprite Image { get; }
		//+коллекция содержащая источники в разрезе ущербов
		bool UpdateBase(int elapsedTime, int damage);
		void LoadMe();
		bool IsPassable();
		bool YouMustRemoveMe();
		bool YouMustUpdateMe();
		bool CanBeDamaged();
		bool CanShowDamage();
		
		void InitState(int state);
		
	}
}

