using Assets.cls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
    public class Starter : MonoBehaviour
    {


        public void Awake()
        {
			StaticSpriteCache.LinkTogoSpritesCache ();
			Square.GroundCache = new Ground ();
            //StaticSpriteCache.LoadCacheFromResources();
            GameController.SendInfo(EnumMyAction.GameBoardReady);
        }
    }
}

