using Assets.cls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;


namespace AssemblyCSharp
{
	public class Beton : ISquareDiv
	{
		
		
		
		
		
		private Dictionary<int, Sprite> StateList;
		private int State;
		private Sprite _image;
		//самый нижний слой, земля. только по ней может ходить человечек.
		public Beton()
		{
			Init();
		}
		public Beton(int state)
		{
			Init();
			InitState(state);
		}
		public void Init()
		{
			_image = null;

			LoadMe();
		}
		//Public Property ConsumeDamage As Damage
		//Public Property AddDamage As Damage
		
		public bool IsPassable()
		{
			return false;
		}
		public void LoadMe()
		{
			//Dim uri As Uri, imgsrc As ImageSource
			StateList = new Dictionary<int, Sprite>();
			//uri = New Uri("images/map/mb_beton.png", UriKind.Relative)
			//imgsrc = New System.Windows.Media.Imaging.BitmapImage(uri)
            //Sprite sp = StaticSpriteCache.sprites[7];
            Sprite sp = StaticSpriteCache.sprites[64];


			StateList.Add(0, sp);
			State = 0;
			UpdateImage();
		}
		private void UpdateImage()
		{
			_image=Base;
		}
		
		
		public Sprite Base {
			get { return StateList[State]; }
		}
		
		public bool UpdateBase(int elapsedTime, int damage)
		{
			this.State = damage;
			return false;
		}
		
		public Sprite Image {
			get { return _image; }
		}
		public bool YouMustRemoveMe()
		{
			if (this.State == StateList.Count - 1) {
				return true;
			} else {
				return false;
			}
		}
		public bool YouMustUpdateMe()
		{
			return false;
		}
		
		public bool CanBeDamaged()
		{
			return false;
		}
		
		public bool CanShowDamage()
		{
			return false;
		}
		
		public void InitState(int state)
		{
			this.State = state;
		}
	}
}

