//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Enums
{
	public enum DecalType
	{
		None = 0,
		Rock = 1,
		Sand = 2
	}
	public enum WhoIs
	{
		Ground = 1,
		Bomb = 2
	}
	public enum Side
	{
		Left = 1,
		Right = 2,
		Up = 3,
		Down = 4
	}
}

