//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public enum EnumMyAction
		{
		Axe = 1,
		Move = 0,
		BeDead = 2,
		ShopReady = 3,
		RoundBegin = 4,
		GameBoardReady = 5,
		LobbyReady = 6,
		CurtainReady = 7,
		Hands = 8,
        Idle=9
		}
}

